FROM openjdk:8-jdk-alpine
VOLUME /tmp
MAINTAINER rrajaram@pivotal.io
ADD target/order-0.0.1-SNAPSHOT.jar order.jar

ENV JAVA_OPTS=""
ENV SPRING_PROFILE="default"
ENV DOCKER_HOST="tcp://localhost:2376"

ENTRYPOINT exec java $JAVA_OPTS \
 -Djava.security.egd=file:/dev/./urandom \
 -Dspring.profiles.active=$SPRING_PROFILE \
 -jar order.jar