/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.workshops.pkskafka.domain.events.order;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum LineItemState {
  placed, in_process, validated, insufficient_inventory, canceled  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LineItemState\",\"namespace\":\"io.pivotal.workshops.pkskafka.domain.events.order\",\"symbols\":[\"placed\",\"in_process\",\"validated\",\"insufficient_inventory\",\"canceled\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
