/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.workshops.pkskafka.inventory.domain.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Inventory extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4385762729338364360L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Inventory\",\"namespace\":\"io.pivotal.workshops.pkskafka.inventory.domain.events\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\",\"doc\":\"Sku of the product\"},{\"name\":\"quantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Inventory> ENCODER =
      new BinaryMessageEncoder<Inventory>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Inventory> DECODER =
      new BinaryMessageDecoder<Inventory>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Inventory> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Inventory> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Inventory>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Inventory to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Inventory from a ByteBuffer. */
  public static Inventory fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Sku of the product */
  @Deprecated public java.lang.CharSequence sku;
  @Deprecated public int quantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Inventory() {}

  /**
   * All-args constructor.
   * @param sku Sku of the product
   * @param quantity The new value for quantity
   */
  public Inventory(java.lang.CharSequence sku, java.lang.Integer quantity) {
    this.sku = sku;
    this.quantity = quantity;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sku;
    case 1: return quantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sku = (java.lang.CharSequence)value$; break;
    case 1: quantity = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sku' field.
   * @return Sku of the product
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }

  /**
   * Sets the value of the 'sku' field.
   * Sku of the product
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public java.lang.Integer getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Integer value) {
    this.quantity = value;
  }

  /**
   * Creates a new Inventory RecordBuilder.
   * @return A new Inventory RecordBuilder
   */
  public static io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder newBuilder() {
    return new io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder();
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Inventory RecordBuilder
   */
  public static io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder newBuilder(io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder other) {
    return new io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder(other);
  }

  /**
   * Creates a new Inventory RecordBuilder by copying an existing Inventory instance.
   * @param other The existing instance to copy.
   * @return A new Inventory RecordBuilder
   */
  public static io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder newBuilder(io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory other) {
    return new io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder(other);
  }

  /**
   * RecordBuilder for Inventory instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Inventory>
    implements org.apache.avro.data.RecordBuilder<Inventory> {

    /** Sku of the product */
    private java.lang.CharSequence sku;
    private int quantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Inventory instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quantity)) {
        this.quantity = data().deepCopy(fields()[1].schema(), other.quantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sku' field.
      * Sku of the product
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }

    /**
      * Sets the value of the 'sku' field.
      * Sku of the product
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sku = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * Sku of the product
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sku' field.
      * Sku of the product
      * @return This builder.
      */
    public io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder clearSku() {
      sku = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public java.lang.Integer getQuantity() {
      return quantity;
    }

    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder setQuantity(int value) {
      validate(fields()[1], value);
      this.quantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public io.pivotal.workshops.pkskafka.inventory.domain.events.Inventory.Builder clearQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Inventory build() {
      try {
        Inventory record = new Inventory();
        record.sku = fieldSetFlags()[0] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.quantity = fieldSetFlags()[1] ? this.quantity : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Inventory>
    WRITER$ = (org.apache.avro.io.DatumWriter<Inventory>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Inventory>
    READER$ = (org.apache.avro.io.DatumReader<Inventory>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
