/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.workshops.pkskafka.inventory.domain.events;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum State {
  placed, validated, in_review, canceled, in_fulfillment  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"io.pivotal.workshops.pkskafka.inventory.domain.events\",\"symbols\":[\"placed\",\"in_review\",\"canceled\",\"in_fulfillment\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
