/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.order.model.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Product {
  JUMPERS, UNDERPANTS, STOCKINGS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Product\",\"namespace\":\"io.pivotal.order.model.avro\",\"symbols\":[\"JUMPERS\",\"UNDERPANTS\",\"STOCKINGS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
