/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.workshops.pkskafka.domain.events.ordervalidation;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderValidationResult {
  PASS, FAIL, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderValidationResult\",\"namespace\":\"io.pivotal.workshops.pkskafka.domain.events.ordervalidation\",\"symbols\":[\"PASS\",\"FAIL\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
