/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pivotal.workshops.pkskafka.domain.events.ordervalidation;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderValidationType {
  INVENTORY_CHECK, FRAUD_CHECK, ORDER_DETAILS_CHECK, CREDIT_CHECK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderValidationType\",\"namespace\":\"io.pivotal.workshops.pkskafka.domain.events.ordervalidation\",\"symbols\":[\"INVENTORY_CHECK\",\"FRAUD_CHECK\",\"ORDER_DETAILS_CHECK\",\"CREDIT_CHECK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
